- unarchive:
   src: https://wordpress.org/latest.tar.gz
   dest: /tmp/
   remote_src: true
- name: remove the html folder
  command: /usr/bin/rm -rf /var/www/html
- name: move wordpress
  command: /usr/bin/mv /tmp/wordpress /var/www/html
- name: copy the template to the host
  template: src=wp-config.j2 dest=/var/www/html/wp-config.php

