- name: create if it doesnt exist
  file: state=touch path=/var/www/html/index.html

- name: if hostname not there add to it
  lineinfile:
    state: present
    dest: /var/www/html/index.html
    line: Hostname={{ansible_hostname}}

